from _typeshed import Incomplete

class DumbDisplay:
    jobs: Incomplete
    out: Incomplete
    errors: Incomplete
    error_filter: Incomplete
    messages: Incomplete
    def __init__(self, error_filter: Incomplete | None = ...) -> None: ...
    def print_message(self, key, msg) -> None: ...
    def add_job(self, key, name) -> None: ...
    def error_handler(self, job, xcptn) -> None: ...
    def report(self) -> None: ...
    def __call__(self, msg) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_val, exc_tb): ...
    def wait(self) -> None: ...
