class Display:
    def __init__(self) -> None: ...
    def report(self) -> None: ...
    def __call__(self, msg) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type, exc_val, exc_tb): ...
