from _typeshed import Incomplete

class termcap(dict):
    def __init__(self, cap_list) -> None: ...
    def getstr(self, capname) -> None: ...
    def getnum(self, capname) -> None: ...
    def getflag(self, capname) -> None: ...

class ostream:
    fo: Incomplete
    caps: Incomplete
    extra: Incomplete
    def __init__(self, fo, caps, extra: Incomplete | None = ...) -> None: ...
    def __lshift__(self, q): ...

class TermApp(ostream):
    required_caps: Incomplete
    input: Incomplete
    output: Incomplete
    def __init__(self) -> None: ...
    orig_attr: Incomplete
    new_attr: Incomplete
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
    def restore_term(self) -> None: ...
    def setup_term(self) -> None: ...
    def set_im(self, vt, vm) -> None: ...
    def refresh_size(self) -> None: ...
    def get_cols(self): ...
    def get_lines(self): ...
    def clear(self): ...
    def set_fg(self, c): ...
    def set_bg(self, c): ...
    def set_bold(self): ...
    def set_rv(self): ...
    def set_ul(self): ...
    def moveyx(self, y, x): ...
    def movexy(self, x, y): ...
    def move_down(self, n: int = ...): ...
    def move_up(self, n: int = ...): ...
    def move_left(self, n: int = ...): ...
    def move_right(self, n: int = ...): ...
    def cr(self): ...
    def save_pos(self): ...
    def restore_pos(self): ...
    def cursor_on(self): ...
    def cursor_off(self): ...
    def reset_color(self): ...
