from .registry import Serialiser

class SerNamedTuple(Serialiser):
    def __init__(self, cls) -> None: ...
    def encode(self, obj, make_rec): ...
    def decode(self, cls, data): ...

class SerAutoNamedTuple(Serialiser):
    def __init__(self) -> None: ...
    def encode(self, obj, make_rec): ...
    def decode(self, cls, data): ...

def is_namedtuple(obj): ...
def namedtuple_hook(obj): ...
def registry(): ...
