from .registry import Serialiser

class PickleString(Serialiser):
    def __init__(self, cls) -> None: ...
    def encode(self, obj, make_rec): ...
    def decode(self, cls, data): ...

def registry(): ...
