from _typeshed import Incomplete

def echo_add(x, y): ...
def add(x, y): ...
def log_add(a, b): ...
def sub(x, y): ...
def mul(x, y): ...
def accumulate(lst, start: int = ...): ...
def get_workflow_graph(promise): ...
def display_workflows(prefix, **kwargs): ...
def snip_line(line, max_width, split_at): ...
def display_text(text, highlight: Incomplete | None = ..., max_width: int = ..., split_at: Incomplete | None = ...) -> None: ...
def run_and_print_log(workflow, highlight: Incomplete | None = ...): ...
